var dispOrder = [ { id: 19,
    suite_id: 3,
    name: 'New Starter via HR',
    description: null,
    parent_id: null,
    display_order: 2,
    depth: 0 },
  { id: 26,
    suite_id: 3,
    name: 'New Starter via Online Recruitment',
    description: null,
    parent_id: null,
    display_order: 3,
    depth: 0 },
  { id: 27,
    suite_id: 3,
    name: 'Applicant with an existing account',
    description: null,
    parent_id: 26,
    display_order: 19,
    depth: 1 },
  { id: 28,
    suite_id: 3,
    name: 'New applicant',
    description: null,
    parent_id: 26,
    display_order: 20,
    depth: 1 },
  { id: 29,
    suite_id: 3,
    name: 'Agency',
    description: null,
    parent_id: 26,
    display_order: 21,
    depth: 1 },
  { id: 30,
    suite_id: 3,
    name: 'Recruitment - Convert Applicant to HR',
    description: null,
    parent_id: 26,
    display_order: 22,
    depth: 1 },
  { id: 22,
    suite_id: 3,
    name: 'New Starter Checks',
    description: null,
    parent_id: null,
    display_order: 25,
    depth: 0 },
  { id: 14,
    suite_id: 3,
    name: 'Administration',
    description: null,
    parent_id: null,
    display_order: 26,
    depth: 0 },
  { id: 23,
    suite_id: 3,
    name: 'Manually Create a User Account',
    description: null,
    parent_id: 14,
    display_order: 27,
    depth: 1 },
  { id: 24,
    suite_id: 3,
    name: 'Auto Generate Account',
    description: null,
    parent_id: 14,
    display_order: 28,
    depth: 1 },
  { id: 15,
    suite_id: 3,
    name: 'Self Service',
    description: null,
    parent_id: null,
    display_order: 29,
    depth: 0 },
  { id: 16,
    suite_id: 3,
    name: 'Manager',
    description: null,
    parent_id: null,
    display_order: 30,
    depth: 0 },
  { id: 18,
    suite_id: 3,
    name: 'Payroll',
    description: null,
    parent_id: null,
    display_order: 32,
    depth: 0 },
  { id: 88,
    suite_id: 3,
    name: 'Payroll New Starter Form',
    description: null,
    parent_id: 18,
    display_order: 33,
    depth: 1 } ],

    cases = [ { id: 43,
    title: 'Search Vacancies',
    section_id: 27,
    type_id: 2,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413894689,
    updated_by: 2,
    updated_on: 1414492800,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: 'This test case assumes that the user already has an existing login for the Cascade Online Recruitment site. Or you may use the admin account:\r\n',
    custom_steps_separated: [ [Object], [Object], [Object] ] },
  { id: 46,
    title: 'Create a New Account',
    section_id: 28,
    type_id: 2,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413894711,
    updated_by: 2,
    updated_on: 1414488935,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object], [Object] ] },
  { id: 3,
    title: 'Create and Publish a New Vacancy',
    section_id: 26,
    type_id: 2,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413795114,
    updated_by: 2,
    updated_on: 1413886341,
    estimate: '10m',
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated:
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ] },
  { id: 41,
    title: 'Navigate to Online Recruitment',
    section_id: 26,
    type_id: 2,
    priority_id: 4,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413886603,
    updated_by: 2,
    updated_on: 1413894884,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object] ] },
  { id: 27,
    title: 'Enter a New Starter',
    section_id: 19,
    type_id: 2,
    priority_id: 4,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413814144,
    updated_by: 2,
    updated_on: 1414073007,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object], [Object] ] },
  { id: 44,
    title: 'Apply for a Vacancy',
    section_id: 27,
    type_id: 2,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413894696,
    updated_by: 2,
    updated_on: 1414488935,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: 'This test case assumes that there are existing Active Vacancies and the user is already logged into Online Recruitment as an existing user.\r\n',
    custom_steps_separated: [ [Object], [Object], [Object] ] },
  { id: 49,
    title: 'Create a New Agency',
    section_id: 29,
    type_id: 2,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413894745,
    updated_by: 2,
    updated_on: 1414512996,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: 'Ensure you are logged out of Online Recruitment.',
    custom_steps_separated: [ [Object], [Object], [Object], [Object], [Object], [Object] ] },
  { id: 45,
    title: 'Search Vacancies',
    section_id: 28,
    type_id: 2,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413894706,
    updated_by: 2,
    updated_on: 1414512738,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: 'Ensure you are logged out of Online Recruitment.',
    custom_steps_separated: [ [Object] ] },
  { id: 47,
    title: 'Apply for a Vacancy',
    section_id: 28,
    type_id: 2,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413894718,
    updated_by: 2,
    updated_on: 1414488935,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object] ] },
  { id: 51,
    title: 'Create a New Applicant',
    section_id: 29,
    type_id: 2,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413894755,
    updated_by: 2,
    updated_on: 1414488935,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object] ] },
  { id: 52,
    title: 'Apply for a Vacancy',
    section_id: 29,
    type_id: 2,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413894759,
    updated_by: 2,
    updated_on: 1414488935,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object], [Object] ] },
  { id: 54,
    title: 'Accept an Application',
    section_id: 30,
    type_id: 2,
    priority_id: 4,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413894788,
    updated_by: 2,
    updated_on: 1414165216,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object], [Object] ] },
  { id: 53,
    title: 'View the Applicant Log',
    section_id: 30,
    type_id: 2,
    priority_id: 4,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413894777,
    updated_by: 2,
    updated_on: 1414163777,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object] ] },
  { id: 55,
    title: 'Convert Applicant to HR',
    section_id: 30,
    type_id: 2,
    priority_id: 4,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413894793,
    updated_by: 2,
    updated_on: 1414165404,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object] ] },
  { id: 28,
    title: 'Check New Starter Workflow',
    section_id: 22,
    type_id: 2,
    priority_id: 4,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413882899,
    updated_by: 2,
    updated_on: 1414689409,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object] ] },
  { id: 29,
    title: 'Auto Enrolment',
    section_id: 22,
    type_id: 2,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413882934,
    updated_by: 2,
    updated_on: 1414488999,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: 'NOTE: This test varies, depending on the method of inputting the New Starter.',
    custom_steps_separated:
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ] },
  { id: 32,
    title: 'Auto Generate a new Account',
    section_id: 24,
    type_id: 2,
    priority_id: 4,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413883732,
    updated_by: 2,
    updated_on: 1414489047,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated:
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ] },
  { id: 30,
    title: 'Organisation Chart',
    section_id: 22,
    type_id: 2,
    priority_id: 1,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413882944,
    updated_by: 2,
    updated_on: 1414488684,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object], [Object], [Object] ] },
  { id: 176,
    title: 'Create a New Profile',
    section_id: 14,
    type_id: 2,
    priority_id: 1,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1414412408,
    updated_by: 2,
    updated_on: 1414488884,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object], [Object] ] },
  { id: 33,
    title: 'Create a new Authorisation Route',
    section_id: 14,
    type_id: 2,
    priority_id: 4,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413883767,
    updated_by: 2,
    updated_on: 1414489935,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object] ] },
  { id: 31,
    title: 'Create a User Account',
    section_id: 23,
    type_id: 2,
    priority_id: 4,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413883707,
    updated_by: 2,
    updated_on: 1414489047,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated:
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ] },
  { id: 177,
    title: 'Create a New Role',
    section_id: 14,
    type_id: 2,
    priority_id: 1,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1414412412,
    updated_by: 2,
    updated_on: 1414488884,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object], [Object] ] },
  { id: 20,
    title: 'Login as New Starter',
    section_id: 15,
    type_id: 6,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413795114,
    updated_by: 2,
    updated_on: 1414489837,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object] ] },
  { id: 21,
    title: 'Update BANK screen',
    section_id: 15,
    type_id: 6,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413795114,
    updated_by: 2,
    updated_on: 1414489946,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object], [Object] ] },
  { id: 22,
    title: 'Update MEDICAL screen',
    section_id: 15,
    type_id: 6,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413795114,
    updated_by: 2,
    updated_on: 1414490019,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object], [Object] ] },
  { id: 23,
    title: 'Update NEXT OF KIN screen',
    section_id: 15,
    type_id: 6,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413795114,
    updated_by: 2,
    updated_on: 1414490078,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object], [Object] ] },
  { id: 24,
    title: 'Submit a Holiday Request',
    section_id: 15,
    type_id: 6,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413795114,
    updated_by: 2,
    updated_on: 1414665306,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object], [Object] ] },
  { id: 34,
    title: 'Submit an Expense Request',
    section_id: 15,
    type_id: 2,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413883791,
    updated_by: 2,
    updated_on: 1414490154,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object], [Object] ] },
  { id: 25,
    title: 'View Pending Requests',
    section_id: 16,
    type_id: 6,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413795114,
    updated_by: 2,
    updated_on: 1414683157,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object] ] },
  { id: 35,
    title: 'Configure New Starter for Payroll Web Integration',
    section_id: 16,
    type_id: 2,
    priority_id: 4,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413883818,
    updated_by: 2,
    updated_on: 1414688046,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object], [Object] ] },
  { id: 224,
    title: 'Check Email Queue',
    section_id: 16,
    type_id: 2,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1414508097,
    updated_by: 2,
    updated_on: 1414682268,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object] ] },
  { id: 36,
    title: 'Integrate New Starter',
    section_id: 18,
    type_id: 2,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413883832,
    updated_by: 2,
    updated_on: 1414690061,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object], [Object] ] },
  { id: 37,
    title: 'Calculate New Starter',
    section_id: 18,
    type_id: 2,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1413883889,
    updated_by: 2,
    updated_on: 1415007124,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object] ] },
  { id: 170,
    title: 'Run Reports',
    section_id: 18,
    type_id: 2,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 3,
    created_on: 1414079218,
    updated_by: 2,
    updated_on: 1415007731,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object], [Object], [Object], [Object] ] },
  { id: 172,
    title: 'Run the GL',
    section_id: 18,
    type_id: 2,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 3,
    created_on: 1414079230,
    updated_by: 2,
    updated_on: 1415015095,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object] ] },
  { id: 171,
    title: 'Run the BACS',
    section_id: 18,
    type_id: 2,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 3,
    created_on: 1414079222,
    updated_by: 2,
    updated_on: 1415012534,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object], [Object] ] },
  { id: 173,
    title: 'Send the Full Payment Submission',
    section_id: 18,
    type_id: 2,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 3,
    created_on: 1414079249,
    updated_by: 2,
    updated_on: 1415016898,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated:
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ] },
  { id: 174,
    title: 'Perform a Period End',
    section_id: 18,
    type_id: 2,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 3,
    created_on: 1414079254,
    updated_by: 2,
    updated_on: 1415096600,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated:
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ] },
  { id: 175,
    title: 'Real Time Information',
    section_id: 18,
    type_id: 2,
    priority_id: 3,
    milestone_id: null,
    refs: null,
    created_by: 3,
    created_on: 1414079271,
    updated_by: 2,
    updated_on: 1415097024,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated:
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ] },
  { id: 223,
    title: 'Enter a New Starter',
    section_id: 88,
    type_id: 2,
    priority_id: 4,
    milestone_id: null,
    refs: null,
    created_by: 2,
    created_on: 1414505816,
    updated_by: 2,
    updated_on: 1415097280,
    estimate: null,
    estimate_forecast: null,
    suite_id: 3,
    custom_status: null,
    custom_preconds: null,
    custom_steps_separated: [ [Object], [Object], [Object], [Object] ] } ];

dispOrder = dispOrder.sort(function(a,b) {
    return a.id - b.id;
});

sectionIds = dispOrder.map(function(e) {return e.id;});
sectionPositions = dispOrder.map(function(e) {return e.display_order;});

cases.forEach(function(e, i, o) {
    cases[i].display_order = sectionPositions[sectionIds.indexOf(e.section_id)];
});

cases = cases.sort(function(a,b) {
    return a.display_order - b.display_order;
});
